# Generated by Django 3.2.5 on 2021-07-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.TextField(verbose_name='Vacancy name')),
                ('companyName', models.TextField(verbose_name='Employing Company')),
                ('companyLocation', models.TextField(verbose_name='Company address')),
                ('c_url', models.URLField(blank=True, db_index=True, unique=True, verbose_name='Company URL')),
                ('salary', models.IntegerField()),
                ('p_date', models.TextField(verbose_name='Vacancy posting date')),
                ('details', models.TextField(verbose_name='Job details')),
                ('informLink', models.URLField(blank=True, db_index=True, unique=True, verbose_name='additional information')),
            ],
        ),
    ]
