# Generated by Django 3.2.5 on 2021-07-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'All junior python developer vacancies'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.TextField(),
        ),
    ]
