# Generated by Django 3.2.5 on 2021-07-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0006_alter_vacancy_c_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.UniqueConstraint(fields=('jobTitle', 'companyName', 'details'), name='Vacancy_must_be_unique'),
        ),
    ]
